"""users

Revision ID: 1340d846c879
Revises:
Create Date: 2025-02-08 18:48:41.954403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "1340d846c879"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("email", sqlalchemy_utils.types.email.EmailType(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("sur_name", sa.String(), nullable=False),
        sa.Column("token_expire", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "password", sqlalchemy_utils.types.password.PasswordType(), nullable=False
        ),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("client", "author", "admin", name="roleenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
