"""event

Revision ID: 2cdb7adfa4ff
Revises: 12a412fa2f0f
Create Date: 2025-02-13 01:34:52.602673

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cdb7adfa4ff"
down_revision: Union[str, None] = "12a412fa2f0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "event_type", sa.Enum("reservation", name="eventtypeenum"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.Column(
            "event_status",
            sa.Enum(
                "pending",
                "resolved",
                "deleted",
                "canceled",
                "failed",
                name="eventstatusenum",
            ),
            nullable=False,
            server_default="pending",
        ),
    )
    op.create_table(
        "reservation_queue",
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["book_id"], ["book.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["client.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reservation_queue")
    op.drop_table("event")
    # ### end Alembic commands ###
