"""adding constraint on phone_number

Revision ID: 3ba4d26a307c
Revises: 354f35c95148
Create Date: 2025-02-08 23:35:50.466093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba4d26a307c'
down_revision: Union[str, None] = '354f35c95148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint("valid_mobile_phone", "user", "phone_number ~ '^09[0-9]{9}$'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("valid_mobile_phone", "user")
    # ### end Alembic commands ###
