"""adding returned to reservation

Revision ID: f82e47403760
Revises: 2cdb7adfa4ff
Create Date: 2025-02-13 08:03:15.919237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f82e47403760"
down_revision: Union[str, None] = "2cdb7adfa4ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reservation",
        sa.Column(
            "returned", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reservation", "returned")
    # ### end Alembic commands ###
